
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasklinker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - 3306:3306
    volumes:
      - tasklinker_database:/var/lib/mysql
    
###< doctrine/doctrine-bundle ###
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - database

volumes:
  tasklinker_database:
